services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./config/mongo/mongo-init.sh:/mongo-init.sh:ro
    command: ["bash", "/mongo-init.sh"]

  cloudshapes:
    image: ${DOCKER_REGISTRY-}cloudshapes
    build:
      context: ../../
      dockerfile: ./src/CloudShapes.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      DATABASE__CONNECTIONSTRING: mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo