name: Build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  workflow_call:

env:
  SOLUTION: ./CloudShapes.sln

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['9.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Pull latest version tag
        if: github.event_name != 'pull_request'
        run: |
          git fetch
          git pull

      - name: Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION }}" --configuration Release --no-restore
      
      - name: Cache
        if: github.event_name != 'pull_request'
        uses: actions/cache@v3
        id: build-dotnet-cache
        with:
          path: ./**/Release/*.nupkg
          key: build-dotnet-cache-${{ github.sha }}